#Routes gerant les fonctionnalités des candidats:
front_office_emploi_candidat_createCV:
    path:     /createCV
    defaults: { _controller: FrontOfficeEmploiBundle:Candidat:createCV }

front_office_emploi_candidat_createLM:
    path:     /createLM
    defaults: { _controller: FrontOfficeEmploiBundle:Candidat:createLM }

front_office_emploi_candidat_showMyCv:
    path:     /showMyCv 
    defaults: { _controller: FrontOfficeEmploiBundle:Candidat:showMyCv}

front_office_emploi_candidat_showMyLm:
    path:     /showMyLm 
    defaults: { _controller: FrontOfficeEmploiBundle:Candidat:showMyLm}

#Routes gerant les offres d'emploi:
front_office_emploi_jobOffer_showOne:
    path:     /showOneJobOffer/{id}
    defaults: { _controller: FrontOfficeEmploiBundle:JobOffer:showOneJobOffer}
    requirements:
        id: "[0-9]+"

front_office_emploi_jobOffer_responseJobOffer:
    path:     /responseJobOffer/{id}
    defaults: { _controller: FrontOfficeEmploiBundle:JobOffer:responseJobOffer}
    requirements:
        id: "[0-9]+"

front-office_emploi_jobOffer_getResponseJobOffer:
    path:     /getResponseJobOffer/{id}
    defaults: { _controller: FrontOfficeEmploiBundle:JobOffer:getResponseJobOffer}
    requirements:
        id: "[0-9]+"

#Routes gérant les fonctionnalités des employeurs:
front_office_emploi_employer_createSociety:
    path:     /createSociety
    defaults: { _controller: FrontOfficeEmploiBundle:Employer:createSociety}

front_office_emploi_employer_createJobOffer:
    path:     /createJobOffer 
    defaults: { _controller: FrontOfficeEmploiBundle:Employer:createJobOffer}

