#Route gerant les fonctionnalités des candidats:
front_office_emploi_candidat_createCV:
    path:     /createCV
    defaults: { _controller: FrontOfficeEmploiBundle:Candidat:createCV }

front_office_emploi_candidat_createLM:
    path:     /createLM
    defaults: { _controller: FrontOfficeEmploiBundle:Candidat:createLM }

#Routes gérant les fonctionnalités des employeurs:
front_office_emploi_employer_createSociety:
    path:     /createSociety
    defaults: { _controller: FrontOfficeEmploiBundle:Employer:createSociety}

front_office_emploi_employer_createJobOffer:
    path:     /createJobOffer 
    defaults: { _controller: FrontOfficeEmploiBundle:Employer:createJobOffer}

