# Route gerant les fonctionnalites communes candidats/employeurs:
# Voir espace personnel candidat:
front_office_emploi_myProfil:
    path:     /myProfil/{$user}
    defaults: { _controller: FrontOfficeEmploiBundle:Profil:myProfil}

front_office_emploi_myJobOffers_list:
    path:     /listMyJobOffers 
    defaults: { _controller: FrontOfficeEmploiBundle:Profil:listMyJobOffers}

front_office_emploi_listMyResponseJobOffers:
    path:     /listMyResponseJobOffers/{id}
    defaults: { _controller: FrontOfficeEmploiBundle:Profil:listMyResponseJobOffers}

# Routes gerant les fonctionnalités des candidats:
# Enregistrement du CV:
front_office_emploi_candidat_createCV:
    path:     /createCV
    defaults: { _controller: FrontOfficeEmploiBundle:Candidat:createCV}

# Enregistrement de la LM:
front_office_emploi_candidat_createLM:
    path:     /createLM
    defaults: { _controller: FrontOfficeEmploiBundle:Candidat:createLM}

# Function voir ses CV dans son espace perso :
front_office_emploi_candidat_showMyCv:
    path:     /showMyCv 
    defaults: { _controller: FrontOfficeEmploiBundle:Candidat:showMyCv}

# Function voir ses LM dans son espace perso :
front_office_emploi_candidat_showMyLm:
    path:     /showMyLm 
    defaults: { _controller: FrontOfficeEmploiBundle:Candidat:showMyLm}

# Function de suppression d'un CV de son espace perso :
front_office_emploi_candidat_deleteCv:
    path:     /deleteCv/{id}
    defaults: { _controller: FrontOfficeEmploiBundle:Candidat:deleteCv}
    requirements:
        id: "[0-9]+"

# Function de suppression d'une LM de son espace perso :
front_office_emploi_candidat_deleteLm:
    path:     /deleteLm/{id}
    defaults: { _controller: FrontOfficeEmploiBundle:Candidat:deleteLm}
    requirements:
        id: "[0-9]+"

# Function de mise à jour d'un CV dans son espace perso :
front_office_emploi_candidat_updateCv:
    path:     /updateCv/{id}
    defaults: { _controller: FrontOfficeEmploiBundle:Candidat:updateCv}
    requirements:
        id: "[0-9]+"

# Function de mise à jour d'une LM dans son espace perso :
front_office_emploi_candidat_updateLm:
    path:     /updateLm/{id}
    defaults: { _controller: FrontOfficeEmploiBundle:Candidat:updateLm}
    requirements:
        id: "[0-9]+"

# Function Voir ses inscriptions à différents évenements dans son espace perso :
front_office_emploi_candidat_showMyInscriptions:
    path:     /showMyInscriptions 
    defaults: { _controller: FrontOfficeEmploiBundle:Candidat:showMyInscriptions}

# Function créer son profil Candidat dans son espace perso :
front_office_emploi_candidat_new:
    path:     /newCandidat
    defaults: { _controller: FrontOfficeEmploiBundle:Candidat:new}

# Function de mise à jour de son profil perso :
front_office_emploi_candidat_update:
    path:     /update/{id}
    defaults: { _controller: FrontOfficeEmploiBundle:Candidat:update}
    requirements:
        id: "[0-9]+"

# Routes gerant les offres d'emploi:
front_office_emploi_jobOffer_showOne:
    path:     /showOneJobOffer/{id}
    defaults: { _controller: FrontOfficeEmploiBundle:JobOffer:showOneJobOffer}
    requirements:
        id: "[0-9]+"

# Selection des jobOffers par criteres:
front_office_emploi_jobOffer_select:
    path:     /selectJobOffer/{id}
    defaults: { _controller: FrontOfficeEmploiBundle:JobOffer:select}
    requirements:
        id: "[0-9]+"

# Function de reponse a une jobOffer:
front_office_emploi_jobOffer_responseJobOffer:
    path:     /responseJobOffer/{id}
    defaults: { _controller: FrontOfficeEmploiBundle:JobOffer:responseJobOffer}
    requirements:
        id: "[0-9]+"

# Routes gérant les fonctionnalités des employeurs:
# Enregistrer une société - créer son espace employer:
front_office_emploi_employer_createSociety:
    path:     /createSociety
    defaults: { _controller: FrontOfficeEmploiBundle:Employer:createSociety}

# Mise a jour de son espace employer:
front_office_emploi_employer_updateSociety:
    path:     /updateSociety/{id}
    defaults: { _controller: FrontOfficeEmploiBundle:Employer:updateSociety}
    requirements:
        id: "[0-9]+"

# Détail d'une société :
front_office_emploi_employer_oneSociety:
    path:     /oneSociety/{id}
    defaults: { _controller: FrontOfficeEmploiBundle:Employer:oneSociety}
    requirements:
        id: "[0-9]+"

# Publier une jobOffer:
front_office_emploi_employer_createJobOffer:
    path:     /createJobOffer/{id}
    defaults: { _controller: FrontOfficeEmploiBundle:Employer:createJobOffer}

# Liste des societes qui recrutent:
front_office_emploi_employer_list:
    path:     /listSocieties
    defaults: { _controller: FrontOfficeEmploiBundle:Employer:listSocieties}

# Retrait de la liste des postes a pourvoir d'une jobOffer:
front_office_emploi_employer_desactivateJobOffer:
    path:     /desactivateJobOffer/{id}
    defaults: { _controller: FrontOfficeEmploiBundle:Employer:desactivateJobOffer}

# Retrait de sa société de la liste des societes qui recrutent:
front_office_emploi_employer_desactivateSociety:
    path:     /desactivateSociety/{id}
    defaults: { _controller: FrontOfficeEmploiBundle:Employer:desactivateSociety}

# Nombre d'offres publiées par une society:
front_office_emploi_employer_nbJobOffer:
    path:     /nbJobOffer/{id}
    defaults: { _controller: FrontOfficeEmploiBundle:Profil:nbJobOffer}

