<?php

namespace FrontOfficeHomepageBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{
	public function getComments($article_id)
	{
		$query = $this -> getEntityManager()->createQuery('
			SELECT c 
			FROM FrontOfficeHomepageBundle:Comment c 
			Join c.article a
			WHERE a.id LIKE :article_id')
		->setParameter('article_id', $article_id);

		return $query->getResult();
	}

	public function nbComments()
	{
		$query = $this -> getEntityManager()->createQuery('
			SELECT COUNT (c.id)
			FROM FrontOfficeHomepageBundle:Comment c');

		return $query -> getSingleScalarResult();
	}

	public function getUnvalidatedComments()
	{
		$query = $this -> getEntityManager()-> createQuery('
			SELECT c 
			FROM FrontOfficeHomepageBundle:Comment c 
			WHERE c.validAdmin =false
			AND c.censored = false');

		return $query -> getResult();
	}

	public function getCommentsValidated($article_id)
	{
		$query = $this -> getEntityManager()->createQuery('
			SELECT c 
			FROM FrontOfficeHomepageBundle:Comment c 
			JOIN c.article a
			WHERE a.id LIKE :article_id
			AND c.validAdmin = true 
			ORDER BY c.dateCreated DESC')
		->setParameter('article_id', $article_id);

		return $query->getResult();
	}

	public function getCensoredComments()
	{
		$query = $this -> getEntityManager()->createQuery('
			SELECT c 
			FROM FrontOfficeHomepageBundle:Comment c 
			WHERE c.censored = true
			ORDER BY c.dateCreated DESC');

		return $query -> getResult();
	}
}
