<?php

namespace FrontOfficeHomepageBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EtablissementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtablissementRepository extends EntityRepository
{
	public function triEtablissements()
	{
		$query = $this -> getEntitymanager()-> createQuery('
			SELECT e
			FROM FrontOfficeHomepageBundle:Etablissement e 
			JOIN e.formation f 
			GROUP BY f.formationName');

		return $query -> getResult();
	}
}
