<?php

namespace FrontOfficeHomepageBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FormationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormationRepository extends EntityRepository
{
	public function getLastFormations()
	{
		$query = $this -> getEntityManager() -> createQuery('
			SELECT f  
			FROM FrontOfficeHomepageBundle:Formation f
			ORDER BY f.createdAt DESC')
		->setMaxResults(1);
		
		return $query ->getResult();
	}

	public function getFormations($formationType)
	{
		$query = $this -> getEntityManager() -> createQuery('
			SELECT f  
			FROM FrontOfficeHomepageBundle:Formation f
			WHERE f.formationType = :type')
		->setParameter('type', $formationType);
		
		return $query ->getResult();
	}

	public function getNbFormationByType()
	{
		$query = $this -> getEntityManager()->createQuery('
			SELECT f.formationName, COUNT(f.id)  as nb 
			FROM FrontOfficeHomepageBundle:Formation f 
			GROUP BY f.formationType
			ORDER BY nb DESC');

		return $query ->getResult();
	}

	public function getFormationType()
	{
		$query = $this -> getEntityManager()->createQuery('
			SELECT f 
			FROM FrontOfficeHomepageBundle:Formation f 
			GROUP BY f.formationType');

		return $query ->  getResult();
	}

	public function nbFormations()
	{
		$query = $this -> getEntityManager() -> createQuery('
			SELECT COUNT(f.id)
			FROM FrontOfficeHomepageBundle:Formation f');

		return $query -> getSingleScalarResult();
	}
}
