<?php

namespace FrontOfficeHomepageBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ForumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ForumRepository extends EntityRepository
{
	public function getForums()
	{
		$query = $this -> getEntityManager()->createQuery('
			SELECT f 
			FROM FrontOfficeHomepageBundle:Forum f 
			WHERE f.forumDate > :dateForum')
		->setParameter('dateForum', 'now')
		-> setMaxResults(2);

		return $query -> getResult();
	}
}
