<?php

namespace FrontOfficeHomepageBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SubscriberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubscriberRepository extends EntityRepository
{
	public function getSubscriberByFormation()
	{
		$query = $this -> getEntityManager()->createQuery('
			SELECT COUNT(s.id) 
			FROM FrontOfficeHomepageBundle:Subscriber s
			JOIN s.formation f
			GROUP BY f.formationType');

		return $query -> getResult();
	}

	public function triSubscriber()
	{
		$query = $this -> getEntityManager()->createQuery('
			SELECT s 
			FROM FrontOfficeHomepageBundle:Subscriber s 
			JOIN s.formation f 
			GROUP BY f.formationName');

		return $query -> getResult();
	}

	public function getSubscriberByForum()
	{
		$query = $this -> getEntityManager()-> createQuery('
			SELECT s 
			FROM FrontOfficeHomepageBundle:Subscriber s 
			JOIN s.forum f
			GROUP BY f.forumType');

		return $query -> getResult();
	}

	public function triSubscriberByForumName()
	{
		$query = $this -> getEntityManager()->createQuery('
			SELECT s 
			FROM FrontOfficeHomepageBundle:Subscriber s 
			JOIN s.forum f 
			GROUP BY f.forumName');

		return $query -> getResult();
	}
}
         