<?php

namespace FrontOfficeHomepageBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SubscriberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubscriberRepository extends EntityRepository
{
	public function getSubscriber()
	{
		$query = $this -> getEntityManager()->createQuery('
			SELECT s 
			FROM FrontOfficeHomepageBundle:Subscriber s 
			JOIN s.formation f 
			GROUP BY f.formationType');

		return $query -> getResult();
	}
}
