user_bundle:
   resource: "@FrontOfficeUserBundle/Resources/config/routing.yml"

front_office_emploi:
    resource: "@FrontOfficeEmploiBundle/Resources/config/routing.yml"
    prefix:   /

front_office_homepage:
    resource: "@FrontOfficeHomepageBundle/Resources/config/routing.yml"
    prefix:   /

