# Route vers la homepage :
front_office_homepage_homepage:
    path:     /
    defaults: { _controller: FrontOfficeHomepageBundle:Homepage:homepage }

# Routes assurant la gestion des formations + Attribution d'une valeur au paramètre de la requete SQL formationType qui sera la valeur par défault.
front_office_formation_list:
    path:     /formation/{formationType}
    defaults: { _controller: FrontOfficeHomepageBundle:Formation:list, formationType: developpement }
    requirements:
        formationType: (developpement|integration|architecte-logiciel)

front_office_formation_oneFormation:
    path:     /oneFormation/{id}
    defaults: { controller: FrontOfficeHomepageBundle:Formation:oneFormation}

# Routes assurant la gestion des forums:
front_office_forum_list:
    path:     /forum/{forumType}
    defaults: { _controller: FrontOfficeHomepageBundle:Forum:list, forumType: emploi}
    requirements:
        forumType: (emploi|formation)

front_office_forum_oneForum:
    path:     /oneForum/{id}
    defaults: { _controller: FrontOfficeHomepageBundle:Forum:oneForum}

#Routes vers le blog :
front_office_homepage_blog_article:
    path:     /showArticles
    defaults: { _controller:FrontOfficeHomepageBundle:Blog:showArticles}

front_office_homepage_blog_oneArticle:
    path:     /showOnearticle/{id}
    defaults: { _controller:FrontOfficeHomepageBundle:Blog:showOneArticle}

#Route de gestion des commentaires:
front_office_homepage_blog_oneArticle_comment:
    path:     /commentOneArticle/{id}
    defaults: { controller:FrontOfficeHomepageBundle:Blog:createComment}

#Routes gérant les informations statiques:
front_office_homepage_static_mentions_legales:
    path:     /mentions_legales
    defaults: { _controller: FrontOfficeHomepageBundle:Static:mentions}

front_office_homepage_static_conditions_generales:
    path:     /conditions_generales
    defaults: { _controller: FrontOfficeHomepageBundle:Static:conditions}