# Route vers la homepage :
front_office_homepage_homepage:
    path:     /
    defaults: { _controller: FrontOfficeHomepageBundle:Homepage:homepage }

# Routes assurant la gestion des formations + Attribution d'une valeur au paramètre de la requete SQL formationType qui sera la valeur par défault.
front_office_formation_list:
    path:     /formation/{formationType}
    defaults: { _controller: FrontOfficeHomepageBundle:Formation:list, formationType: developpement }
    requirements:
        formationType: (developpement|integration|architecte-logiciel|bdd|reseaux|devMob)

# Selection des formations par type / Choix d'une formation - Attribution de valeur au paramétre formationType dans le lien en homepage
front_office_formation_showOne:
    path:     /formation/{formationType}/{id}
    defaults: { _controller: FrontOfficeHomepageBundle:Formation:showOne}
    requirements:
        formationType: (developpement|integration|architecte-logiciel|bdd|reseaux|devMob)
        id: "[0-9]+"

# Inscription d'un user à une formation:
front_office_formation_inscription:
    path:     /inscriptionFormation/{id}
    defaults: { _controller: FrontOfficeHomepageBundle:Formation:inscription}
    requirements:
        id: "[0-9]+"

# Routes assurant la gestion des forums + Attribution d'une valeur au paramètre de la requete SQL forumType qui sera la valeur par défault.
front_office_forum_list:
    path:     /forum/{forumType}
    defaults: { _controller: FrontOfficeHomepageBundle:Forum:list, forumType: emploi}
    requirements:
        forumType: (emploi|formation)

# Selection des forums par type / Choix d'un forum - Attribution d'une valeur au paramètre grace au lien en homepage
front_office_forum_oneForum:
    path:     /oneForum/{id}
    defaults: { _controller: FrontOfficeHomepageBundle:Forum:oneForum}
    requirements: 
        id: "[0-9]+"

# Inscription d'un user à un forum:
front_office_forum_inscription:
    path:     /inscriptionForum/{id}
    defaults: { _controller: FrontOfficeHomepageBundle:Forum:inscription}
    requirements:
        id: "[0-9]+"

# Routes assurant la gestion du blog :
front_office_homepage_blog_article:
    path:     /showArticles
    defaults: { _controller: FrontOfficeHomepageBundle:Blog:showArticles}

# Selection d'un article avec affichage de ses commentaires:
front_office_homepage_blog_oneArticle:
    path:     /showOnearticle/{id}
    defaults: { _controller: FrontOfficeHomepageBundle:Blog:showOneArticle}

# Selection des articles selon leur category, parametrage en homepage du blog:
front_office_homepage_blog_triArticle:
    path:     /triArticle/{category}
    defaults: { _controller: FrontOfficeHomepageBundle:Blog:triArticles}

front_office_homepage_blog_categories:
    path:     /Categories 
    defaults: { _controller: FrontOfficeHomepageBundle:Blog:list}

# Routes gérant les informations statiques:
front_office_homepage_static_mentions_legales:
    path:     /mentions_legales
    defaults: { _controller: FrontOfficeHomepageBundle:Static:mentions}

front_office_homepage_static_conditions_generales:
    path:     /conditions_generales
    defaults: { _controller: FrontOfficeHomepageBundle:Static:conditions}

front_office_homepage_static_contact:
    path:     /contact 
    defaults: { _controller: FrontOfficeHomepageBundle:Static:contact}

front_office_homepage_static_about:
    path:     /aboutChristophe  
    defaults: { _controller: FrontOfficeHomepageBundle:Static:about}