# Route vers la homepage :
front_office_homepage_homepage:
    path:     /
    defaults: { _controller: FrontOfficeHomepageBundle:Homepage:homepage }

# Routes assurant la gestion des formations + Attribution d'une valeur au paramètre de la requete SQL formationType qui sera la valeur par défault.
front_office_formation_list:
    path:     /formation/{formationType}
    defaults: { _controller: FrontOfficeHomepageBundle:Formation:list, formationType: developpement }
    requirements:
        formationType: (developpement|integration|architecte-logiciel)

front_office_formation_oneFormation:
    path:     /oneFormation/{id}
    defaults: { controller: FrontOfficeHomepageBundle:Formation:oneFormation}

# Routes assurant la gestion des forums + Attribution d'une valeur au paramètre de la requete SQL forumType qui sera la valeur par défault.
front_office_forum_list:
    path:     /forum/{forumType}
    defaults: { _controller: FrontOfficeHomepageBundle:Forum:list, forumType: emploi}
    requirements:
        forumType: (emploi|formation)

front_office_forum_oneForum:
    path:     /oneForum/{id}
    defaults: { _controller: FrontOfficeHomepageBundle:Forum:oneForum}

# Routes gerant l'inscription de participants aux evenements Forum et Formation:
front_office_subscriber_formation:
    path:     /subscriberFormation/{id}
    defaults: { _controller: FrontOfficeHomepageBundle:Subscriber:registrationFormation}

#Routes vers le blog :
front_office_homepage_blog_article:
    path:     /showArticles
    defaults: { _controller: FrontOfficeHomepageBundle:Blog:showArticles}

front_office_homepage_blog_oneArticle:
    path:     /showOnearticle/{id}
    defaults: { _controller: FrontOfficeHomepageBundle:Blog:showOneArticle}

#Route de gestion des commentaires:
# front_office_homepage_createComment:
#     path:     /createComment/{id}
#     defaults: { controller: FrontOfficeHomepageBundle:Comment:createComment}

front_office_homepage_blog_showComments:
    path:     /showComments /{id}
    defaults: { _controller: FrontOfficeHomepageBundle:Comment:showComments}

#Routes gérant les informations statiques:
front_office_homepage_static_mentions_legales:
    path:     /mentions_legales
    defaults: { _controller: FrontOfficeHomepageBundle:Static:mentions}

front_office_homepage_static_conditions_generales:
    path:     /conditions_generales
    defaults: { _controller: FrontOfficeHomepageBundle:Static:conditions}