<?php

namespace FrontOfficeEmploiBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * JobSectorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JobSectorRepository extends EntityRepository
{
	public function getNbJobOffersByJobSector()
	{
		$query = $this -> getEntityManager()->createQuery('
			SELECT j.nameSector, COUNT(job.id) AS nb 
			FROM FrontOfficeEmploiBundle:JobSector j 
			JOIN j.jobOffer job
			GROUP BY j.nameSector
			ORDER BY nb DESC');

		return $query -> getResult();
	}

}