<?php

namespace FrontOfficeEmploiBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PlaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlaceRepository extends EntityRepository
{
	public function getPlaceByNbJobOffers()
	{
		$query = $this -> getEntitymanager()->createQuery('
			SELECT p.name, COUNT(j.id) AS nb 
			FROM FrontOfficeEmploiBundle:Place p 
			JOIN p.jobOffer j 
			GROUP BY p.name
			ORDER BY nb DESC');

		return $query -> getResult();
	}
}
