<?php

namespace FrontOfficeEmploiBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ResponseJobOfferRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResponseJobOfferRepository extends EntityRepository
{
	public function getJobOfferResponse($jobOffer_id)
	{
		$query = $this -> getEntityManager()-> createQuery('
			SELECT r 
			FROM FrontOfficeEmploiBundle:ResponseJobOffer r 
			JOIN  r.jobOffer j
			WHERE j.id LIKE :id')
		->setParameter('id', $jobOffer_id);

		return $query -> getResult();
	}

	public function getJobOfferResponses($societyId)
	{
		$query = $this -> getEntityManager()-> createQuery('
			SELECT r 
			FROM FrontOfficeEmploiBundle:ResponseJobOffer r
			JOIN  r.jobOffer j
			WHERE j.society = :society')
		->setParameter('society', $societyId);

		return $query -> getResult();
	}

	public function getJobOfferResponseByUser($jobOffer_id, $user_id)
	{
		$query = $this -> getEntityManager()-> createQuery('
			SELECT r 
			FROM FrontOfficeEmploiBundle:ResponseJobOffer r 
			JOIN  r.jobOffer j
			JOIN r.user u
			WHERE j.id LIKE :jobOffer_id
			AND u.id  LIKE :user_id')
		->setParameter('jobOffer_id', $jobOffer_id)
		->setParameter('user_id', $user_id);

		return $query -> getResult();
	}	
	
}
