<?php

namespace FrontOfficeEmploiBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SocietyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SocietyRepository extends EntityRepository
{
	public function getSocieties()
	{
		$query = $this -> getEntityManager()->createQuery('
			SELECT s 
			FROM FrontOfficeEmploiBundle:Society s 
			WHERE s.hiringState = true 
			ORDER BY s.dateCreated DESC')
		;

		return $query -> getResult();
	}

	public function nbSociety()
	{
		$query = $this -> getEntityManager()->createQuery('
			SELECT COUNT(s.id)
			FROM FrontOfficeEmploiBundle:Society s');

		return $query -> getSingleScalarResult(); 
	}

	public function triSociety()
	{
		$query = $this -> getEntityManager()->createQuery('
			SELECT s 
			FROM FrontOfficeEmploiBundle:Society s 
			ORDER BY s.dateCreated DESC');

		return $query -> getResult();
	}

	public function getSocietiesByJobSector()
	{
		$query = $this -> getEntityManager()-> createQuery('
			SELECT j, COUNT(s.id) AS nb 
			FROM FrontOfficeEmploiBundle:JobSector j 
			JOIN j.societies s 
			GROUP BY j.nameSector
			ORDER BY s.id DESC');

		return $this -> getResult();
	}

	public function getSocietyByUser($user)
	{
		$query = $this -> getEntityManager()-> createQuery('
			SELECT s 
			FROM FrontOfficeEmploiBundle:Society s 
			JOIN s.user u 
			WHERE u.id LIKE :id
			AND u.personnalSpaceActive = true')
		->setParameter('id', $user);

		return $query -> getSingleResult();
	}

	public function getNbJobOffersBySociety()
	{
		$query = $this -> getEntityManager()-> createQuery('
			SELECT s.name, COUNT(j.id) AS nb
			FROM FrontOfficeEmploiBundle:Society s 
			JOIN s.jobOffer j 
			WHERE j.activeToPurchase = true
			GROUP BY s.name
			ORDER BY nb DESC');

		return $query -> getResult();
	}
}
