#Route gerant la homepage du backoffice:
back_office_homepage:
    path:     /homepageBackoffice
    defaults: { _controller: BackOfficeBundle:Homepage:homepage}

#Routes gerant l'administration des articles:
back_office_adminarticles_list:
    path:     /listArticles
    defaults: { _controller: BackOfficeBundle:AdminArticle:list}

back_office_adminarticles_create:
    path:     /createArticle
    defaults: { _controller: BackOfficeBundle:AdminArticle:createArticle}

back_office_adminarticles_edit:
    path:     /editArticle/{id}
    defaults: { _controller: BackOfficeBundle:AdminArticle:editArticle}
    requirements: 
        id: "[0-9]+"

back_office_adminarticles_delete:
    path:     /deleteArticle/{id}
    defaults: { _controller: BackOfficeBundle:AdminArticle:deleteArticle}
    requirements:
        id: "[0-9]+"

#Routes gerant l'administration des formations:
back_office_adminformation_show:
    path:     /showFormation
    defaults: { _controller: BackOfficeBundle:AdminFormation:showFormation}

back_office_adminformation_edit:
    path:     /editFormation/{id}
    defaults: { _controller: BackOfficeBundle:AdminFormation:editFormation}
    requirements: 
        id: "[0-9]+"

back_office_adminformation_create:
    path:     /createFormation
    defaults: { _controller: BackOfficeBundle:AdminFormation:createFormation}

back_office_adminformation_delete:
    path:     /deleteFormation/{id}
    defaults: { _controller: BackOfficeBundle:AdminFormation:deleteFormation}
    requirements:
        id: "[0-9]+"

back_office_adminformation_triFormations:
    path:     /triFormations
    defaults: { _controller: BackOfficeBundle:AdminFormation:triFormations}

#Routes gerant l'administration des forums:
back_office_adminforum_list:
    path:     /listForums
    defaults: { _controller: BackOfficeBundle:AdminForum:list}

back_office_adminforum_new:
    path:     /newForum
    defaults: { _controller: BackOfficeBundle:AdminForum:new}

back_office_adminforum_showOne:
    path:     /showOneForum/{id}
    defaults: { _controller: BackOfficeBundle:AdminForum:showOne}
    requirements: 
        id: "[0-9]+"

back_office_adminforum_edit:
    path:     /edit/{id}
    defaults: { _controller: BackOfficeBundle:AdminForum:edit}
    requirements:
        id: "[0-9]+"

back_office_adminforum_delete:
    path:     /deleteForum/{id}
    defaults: { _controller: BackOfficeBundle:AdminForum:delete}
    requirements:
        id: "[0-9]+"

back_office_adminforum_triForums:
    path:     /triForums 
    defaults: { _controller: BackOfficeBundle:AdminForum:triForums}

#Routes gerant l'administration des JobSectors: 
back_office_adminJobSector_list:
    path:     /listJobSector
    defaults: { _controller: BackOfficeBundle:AdminJobSector:list}

back_office_adminJobSector_create:
    path:      /createJobSector
    defaults: { _controller: BackOfficeBundle:AdminJobSector:create}

#Routes gerant l'administration des jobOffers:
back_office_adminjobOffers_show:
    path:     /showJobOffers
    defaults: { _controller: BackOfficeBundle:AdminJobOffers:showJobOffers}

back_office_adminjobOffer_edit:
    path:     /editJobOffer/{id}
    defaults: { _controller: BackOfficeBundle:AdminJobOffers:editJobOffer}
    requirements:
        id: "[0-9]+"

back_office_adminjobOffer_delete:
    path:     /deleteJobOffer/{id}
    defaults: { _controller: BackOfficeBundle:AdminJobOffers:deleteJobOffer}
    requirements: 
        id: "[0-9]+"


